export const CONNECTIONS__SET_PROPERTIES = '@@CONNECTIONS__SET_PROPERTIES';

export const LOGS__SET_PROPERTIES = '@@LOGS__SET_PROPERTIES';

export const AGENT_FORM__CLEAR_PROPERTIES = '@@AGENT_FORM__CLEAR_PROPERTIES';
export const AGENT_FORM__SET_PROPERTIES = '@@AGENT_FORM__SET_PROPERTIES';
export const AGENT_LIST__SET_ITEMS = '@@AGENT_LIST__SET_ITEMS';

export const ENTITY_FORM__CLEAR_PROPERTIES = '@@ENTITY_FORM__CLEAR_PROPERTIES';
export const ENTITY_FORM__SET_PROPERTIES = '@@ENTITY_FORM__SET_PROPERTIES';
export const ENTITY_LIST__SET_ITEMS = '@@ENTITY_LIST__SET_ITEMS';

export const NODE_FORM__CLEAR_PROPERTIES = '@@NODE_FORM__CLEAR_PROPERTIES';
export const NODE_FORM__SET_PROPERTIES = '@@NODE_FORM__SET_PROPERTIES';
export const NODE_LIST__SET_ITEMS = '@@NODE_LIST__SET_ITEMS';
